# Please update Haskell image versions under .github/workflows/ci.yml together to use the same GHC version
# (or the CI build will fail)
resolver: lts-21.25
pvp-bounds: both
packages:
  - "."
ghc-options:
  # Build with advanced optimizations enabled by default
  "$locals": -O2 -Werror
extra-deps:
  # As of 2021-11-08, the latest release of `language-javascript` is 0.7.1.0,
  # but it has a problem with parsing the `async` keyword.  It doesn't allow
  # `async` to be used as an object key:
  # https://github.com/erikd/language-javascript/issues/131
  - language-javascript-0.7.0.0
  # Fix issue with libtinfo.
  # See https://github.com/purescript/purescript/issues/4253
  - process-1.6.18.0
  # The Cabal library is not in Stackage
  - Cabal-3.8.1.0
  # hspec versions 2.9.3 to 2.10.6 depend on ghc
  # ghc depends on terminfo by default, but that can be ignored
  # if one uses the '-terminfo' flag.
  # Unfortunately, hspec doesn't expose a similar flag.
  #
  # Using hspec >= 2.10.7 addresses this.
  - hspec-2.10.9
  - hspec-core-2.10.9
  - hspec-discover-2.10.9
  - bower-json-1.1.0.0
  - github: sh-ft/aeson-better-errors
    commit: 6c850aeefaafe44529de5efc7afddf30a9404d5c
  - github: HS-Flensburg-PLTP/cheapskate
    commit: a32d95823bbbd05d11ee496775f108ed09f0c1a7
  - github: HS-Flensburg-PLTP/pattern-arrows
    commit: 1a005d87dd133f4e543924307b840677deba215b
nix:
  packages:
    - zlib
    # Test dependencies
    - nodejs
    - nodePackages.npm
    - nodePackages.bower
flags:
  aeson-pretty:
    lib-only: true
